_target_: jepa.JEPA

encoder:
  _target_: stable_pretraining.backbone.utils.vit_hf
  size: tiny
  patch_size: 14
  image_size: ${img_size}
  pretrained: false
  use_mask_token: false

predictor:
  _target_: module.CfCPredictor
  num_frames: ${history_size}
  input_dim: ${embed_dim}
  hidden_dim: ${embed_dim}
  output_dim: ${embed_dim}
  action_dim: ${embed_dim}
  backbone_activation: silu
  backbone_units: 256
  backbone_layers: 2
  backbone_dr: 0.1
  use_mixed: false

action_encoder:
  _target_: module.Embedder
  input_dim: ???
  emb_dim: ${embed_dim}

projector:
  _target_: module.MLP
  input_dim: ${embed_dim}
  output_dim: ${embed_dim}
  hidden_dim: 2048
  norm_fn:
    _target_: torch.nn.BatchNorm1d
    _partial_: true

pred_proj:
  _target_: module.MLP
  input_dim: ${embed_dim}
  output_dim: ${embed_dim}
  hidden_dim: 2048
  norm_fn:
    _target_: torch.nn.BatchNorm1d
    _partial_: true
